@host=http://localhost:8080


###

GET {{host}}/france

###

GET {{host}}/list

###

POST {{host}}/paymentDetail
Content-Type: application/json

{
  "amount": 100
}

###

POST {{host}}/paymentProxy
Content-Type: application/json
RequestId: 123

{
  "id" : "1",
  "amount": 100
}